# # syntax=docker/dockerfile:1
# syntax=docker/dockerfile:1
FROM python:3.12
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# Install system dependencies
RUN apt-get update && apt-get install -y locales && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen fa_IR.UTF-8
# Set up working directory
WORKDIR /usr/src/app
# Install Python dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt
